"""Add photo_file_id to persons and families

Revision ID: 6b817a4bb027
Revises: 891a5c642654
Create Date: 2026-05-24 13:37:39.860526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b817a4bb027'
down_revision = '891a5c642654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_families_photo_file_id', 'files', ['photo_file_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_persons_photo_file_id', 'files', ['photo_file_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_persons_photo_file_id', type_='foreignkey')
        batch_op.drop_column('photo_file_id')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_constraint('fk_families_photo_file_id', type_='foreignkey')
        batch_op.drop_column('photo_file_id')

    # ### end Alembic commands ###
