"""Add Family model

Revision ID: 891a5c642654
Revises: 0f45d2f7d0f8
Create Date: 2026-05-24 13:25:49.687423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891a5c642654'
down_revision = '0f45d2f7d0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('head_person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('head_person_id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_persons_family_id', 'families', ['family_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_teams_parent_id', 'teams', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    conn = op.get_bind()

    persons = conn.execute(
        sa.text("SELECT id, first_name, last_name FROM persons")
    ).fetchall()

    relationships = conn.execute(
        sa.text(
            "SELECT person_1_id, person_2_id FROM family_relationships"
        )
    ).fetchall()

    graph = {p[0]: set() for p in persons}
    for r in relationships:
        graph.setdefault(r[0], set()).add(r[1])
        graph.setdefault(r[1], set()).add(r[0])

    visited = set()
    for pid in list(graph.keys()):
        if pid in visited:
            continue
        stack = [pid]
        component = set()
        while stack:
            node = stack.pop()
            if node not in visited:
                visited.add(node)
                component.add(node)
                stack.extend(graph.get(node, set()) - visited)

        last_names = [
            p[2]
            for p in persons
            if p[0] in component
        ]
        family_name = (
            f"{max(set(last_names), key=last_names.count)} Family"
            if last_names else None
        )

        result = conn.execute(
            sa.text(
                "INSERT INTO families (name, created_at, updated_at) "
                "VALUES (:name, datetime('now'), datetime('now'))"
            ),
            {"name": family_name},
        )
        family_id = result.lastrowid

        for p_id in component:
            conn.execute(
                sa.text(
                    "UPDATE persons SET family_id = :family_id WHERE id = :p_id"
                ),
                {"family_id": family_id, "p_id": p_id},
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teams_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_persons_family_id', type_='foreignkey')
        batch_op.drop_column('family_id')

    op.drop_table('families')
    # ### end Alembic commands ###
