"""Add MeetingInstance model and FK on files/posts

Revision ID: b055cc69da86
Revises: 46d8b2f65eef
Create Date: 2026-05-24 14:36:47.199894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b055cc69da86'
down_revision = '46d8b2f65eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_instance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_files_meeting_instance_id', 'meeting_instances', ['meeting_instance_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_instance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_posts_meeting_instance_id', 'meeting_instances', ['meeting_instance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_meeting_instance_id', type_='foreignkey')
        batch_op.drop_column('meeting_instance_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_files_meeting_instance_id', type_='foreignkey')
        batch_op.drop_column('meeting_instance_id')

    op.drop_table('meeting_instances')
    # ### end Alembic commands ###
