"""add structured address fields

Revision ID: e75bd76e0094
Revises: f0eead19ffc0
Create Date: 2026-05-25 10:42:37.783553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75bd76e0094'
down_revision = 'f0eead19ffc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_country', sa.String(length=100), nullable=True))

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('address_country')
        batch_op.drop_column('address_postal_code')
        batch_op.drop_column('address_region')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_street')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('address_country')
        batch_op.drop_column('address_postal_code')
        batch_op.drop_column('address_region')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_street')

    # ### end Alembic commands ###
